### ISSUE TITLE
missing or hidden ?

### ISSUE THREAD

**Issue by gitourus** [tantaman/Strut#288]
I spent quite a while looking around, the tool seem OK but something is missing or hidden.
People want to use the tool and deploy a presentation.
The tool is pretty easy to use, but  what about how to deploy a presentation?
I have not seen a word about it, that makes me suspect something is hidden.
How do I put a presentation on my web site?
Is the tool free as free beer or just try it?
Can somebody clarify that?

PS.- zip export not working. 1-Cannot see “present“ button. 2- Ctrl + S saves htm file.

**Comment by iiiGerardoiii** [comment]
I'm doing @kirbyfan64's steps (Cmd+S the website) but I keep getting an error as soon as the download starts:
![captura de pantalla 2019-01-25 17 32 10](https://user-images.githubusercontent.com/6264194/51778469-6bc27e80-20c7-11e9-93ca-5fb134c820fe.png)
I'm doing this on Firefox since Chrome gives me the red "malicious site" screen.

Although it shows "error", the HTML file gets downloaded, but when I open it, the slides show up way off the screen, maybe the html file is incomplete?:

![captura de pantalla 2019-01-25 17 38 57](https://user-images.githubusercontent.com/6264194/51778588-25b9ea80-20c8-11e9-9d05-7830445ca881.png)
(I had to zoom-out in order to see that text)

Anyone knows why this is happening? I just wanna download the html file properly so I can put it on a flash drive and open it on another pc with no internet.
