### ISSUE TITLE
Youtube video is not work

### ISSUE THREAD

**Issue by yarikus** [tantaman/Strut#291]
When I click to play video it's not work.

**Comment by 2braincells2go** [comment]
Anyone ever get this working?

When I add a YT video and view slide nothing but black area where video should show start image. Clicking on black area starts video but users would have no clue to do that.

Tried on Chrome and FF.

**Comment by kirbyfan64** [comment]
Workaround: get the HTML embedding code from the YouTube share button and paste in the Markdown section.

**Comment by 2braincells2go** [comment]
Great idea @kirbyfan64! Thanks for tip.

**Comment by mwcz** [comment]
That tip is the answer to every Strut question. :)

**Comment by tantaman** [comment]
Yeah... Things change and stuff breaks and I'm loaded with other work for
the foreseeable future :o

**Comment by 2braincells2go** [comment]
LOL @mwcz!

If I had the talent @tantaman would attempt to help with issues, but do not. Understand about time though.

**Comment by mwcz** [comment]
Joking aside, I actually really like that this tip is so powerful.  It's one of my favorite things about Strut: it's just a webpage.  And being a webpage means that *anything* you can do on the web, you can do in Strut, via the Markdown tab (because Markdown is a superset of HTML).  Like adding custom css, custom JS, [crazy 3D graphics](http://threejs.org/examples/webgl_materials_cubemap), [interactive charts](http://mbostock.github.io/d3/talk/20111018/force-states.html), etc.

**Comment by 2braincells2go** [comment]
Totally understand what you meant @mwcz. Very powerful feature indeed.
