### ISSUE TITLE
How to share a presentation?

### ISSUE THREAD

**Issue by mdehollander** [tantaman/Strut#341]
I read on strut.io that you can share your presentation with others if you use the hosted solution. But how do you actually do this? I would like to work on a presentation with some collaborators. Is this possible?

Thanks!

**Comment by pmietlicki** [comment]
Hi,
I think that strut in its actual version can not do that, you can import / export your presentation in json format though. I've tried to create a version with server side implementation using PHP, you can check and try it now on [my website](http://pascal-mietlicki.fr/strut) but be aware that it's still in early development, so you could experience some bugs.

The process is simple : create a presentation by entering its name and description (you have to be registered and connected to do that), then click on "Edit". The Edit link is the official write link so avoid to share it or at least work on it one at a time because I have not implemented concurrent writing.

The read links to share it are different between generators : so you can generate and share the impress one, bespoke one or handouts one. Just use the different buttons that appears next to your presentation.

Hope it can help.
Regards,
Pascal

**Comment by 2braincells2go** [comment]
Nice job Pascal. Have been wanting to do something like this to use in classroom. You have any plans to share this on GitHub or is it a private endeavor?

Cheers!

**Comment by pmietlicki** [comment]
This job is nothing compared to the job made to create Strut.

I think I will share it but, before, I'd like to have something stable with as less bugs as possible. So I need as much testers as possible, if you're willing to try it and give me feedbacks, it would be great ! Then, when stable, I will release it under octobercms (that's the PHP platform that I'm using) as an official plugin.

Have a nice day,
Pascal

**Comment by 2braincells2go** [comment]
I must agree Pascal, took a lot to create Strut. Amazed every time I use it.

Will test out yours and give some feedback.

For my needs, got to have something that will run on local server since the younger kids cannot access internet in classroom. Thanks much.

**Comment by zeigerpuppy** [comment]
thanks for this, I'll give it a test drive too!

**Comment by pmietlicki** [comment]
Hi,
It would be great if you could try it and give me your feedbacks (on github, on my website forum or whatever you want). It would be easy to install on a local server since I've made a plugin for octobercms. It takes like 5 mintues to install octobercms on a LAMP server and 5 more to configure it and install the plugin I've made.
Hope to hear from you soon.
Pascal
PS : I've solved some bugs, it should be more "stable" now

**Comment by pmietlicki** [comment]
Here is a [public link](http://pascal-mietlicki.fr/strut/preview/impress/Application+i-Parapheur) to a presentation. That's the kind of unique link that the application will generate and that you can send / share with others by using "Impress" or "Bespoke" or "Handouts" buttons.

**Comment by mdehollander** [comment]
Hi Pascal,

Thanks for an account-based interface to strut. Do you have any plans to implement concurrent-writing? Because the goal of my original question is that I would like to edit the same presentation with multiple people in the same time. Something like etherpad.
A local installation would also be nice.
I will give your implementation a try and let you know how it works.

**Comment by pmietlicki** [comment]
Hi,
Concurrent writing could be difficult to implement. But I plan to treat it by checking the last update of the presentation and, automatically, update all the presentation opened at the same time in writing mode. So yes I'm thinking about it because I've already done it on an other project. But I'll need to test it thoroughly.
A local installation is already possible. As soon as it's stable and if people are interested, I'll share the plugin.
I'm looking forward for your remarks.

**Comment by crti** [comment]
@pmietlicki can you give a statement how long you plan to support http://pascal-mietlicki.fr/strut ? 
Also a short feedback on the current situation of impress.js GUIs like Strut would be welcome as I do not see anything FOSS near to it but having development stalled since over a year is not very reassuring for a long-time usage.
