### ISSUE TITLE
403 when accessing strut.io

### ISSUE THREAD

**Issue by TheNetAdmin** [tantaman/Strut#370]
I've used strut.io to create some slides, it's really awesome. But these days, when accessing the website, I always get 403 forbidden, no matter which device I used... Is there any solution for this situation?

**Comment by mwcz** [comment]
I can't respond to that issue, but you're welcome to use my instance of strut: http://strut-mwcz.rhcloud.com/

**Comment by crti** [comment]
I had played around with Strut in the past and found it one of the most exciting HTML presentation tools. Now I would have an actual presentation I would have liked to try with Strut but the project seems inactive since a year and the site inaccessible :-( 
> 403 Forbidden
>     Code: AllAccessDisabled
>     Message: All access to this object has been disabled
https://github.com/tantaman/strut2 last activity 2 years ago :-(
https://github.com/impress/impress.js seems to be the current link and active :-) 
https://github.com/bespokejs/bespoke last activity 2 years ago :-/

@mwcz: is this the same code version like here? 
Your instance did not load the GUI in my Firefox 50.1.0 @Win10x64 even after allowing Scripts and deactivating uBlock. Only message in Console: 
```
Loaded mirror  codemirror.js:4:1
LOADING LODASH!!!!  lodash.js:11:3
```
In Chromium 57.0.2955.0 the instance GUI loads. I do not remember if Shapes was included and working when I last tried Strut but the dropdown menu content seems to not load correctly. See attachment. Maybe known problem? 

I will now try to use Strut and especially see if I'm able to use a custom font and save the Presentation locally (maybe including with webm Video). Found also this page: http://pascal-mietlicki.fr/strut

**Comment by tantaman** [comment]
sorry guys.  My AWS account had some issue.  http://strut.io is back up and running.
