### ISSUE TITLE
Official website strut.io down

### ISSUE THREAD

**Issue by PhilippeNoel1** [tantaman/Strut#387]
Hello,
Just to tell you the official website [strut.io](strut.io) is down since yesterday.
Any news or informations ?

**Comment by abshda** [comment]
I believe it is the same coinminer thing that happened earlier

**Comment by ejvindh** [comment]
@tantaman has recently revised the Readme-file in order to remove references to the site:
https://github.com/tantaman/Strut/commit/53af6c63948ad841f249d834efcdc46197854495
https://github.com/tantaman/Strut/commit/60e0075f325295716693f227b10b1e6127c5630e

...he missed one, however, on the top of the opening github-page:
https://github.com/tantaman/Strut

But I guess, the message is: Don't count on strut.io anymore, use this site instead:
https://tantaman.github.io/Strut/dist/

**Comment by tantaman** [comment]
re-deployed the site.

Seems to be issues with running presentations on mobile, however.
