### ISSUE TITLE
Assign components to layers

### ISSUE THREAD

**Issue by tantaman** [tantaman/Strut#69]
Test, images, video, etc. should be able to be assigned to a specific layer (z-index).

**Comment by Chaos99** [comment]
Is there a workaround while this is not implemented? Placing some text on top of a shape is almost impossible, as clicking the shape again will always bring it to the top masking the text below. This also sometimes happens without clicking, just by working on another slide.
As mentioned in the other issue, using the z-index CSS parameter doesn't work, possibly because the elements are in different groups internally.

**Comment by tantaman** [comment]
no workaround at the moment :/
